# El nombre de tu plugin. Es correcto.
name: X2
# La versión se tomará automáticamente del archivo pom.xml. ¡Más eficiente!
version: 1.0.1
# La ruta a tu clase principal. Es correcta.
main: me.generador.X2.X2
# La versión de la API. Es correcta.
api-version: '1.20'
# Información adicional. ¡Buen trabajo!
description: Un plugin de prueba.
authors: [Poelsk]