name: FoliaBans-Core
main: com.tudominio.foliabans.core.FoliaBansCore
version: 0.1
api-version: '1.20'
# Dependencia "dura": el Core necesita a ProtocolLib para funcionar.
depend:
  - ProtocolLib
  - FoliaBans